pool: testpool

trigger: 
- main

variables:
  Work_dir: '$(System.DefaultWorkingDirectory)/modules/dev'

stages:
  - stage: terraforminitandplan
    displayName: Terraform init and Plan
    jobs:
      - job: terraforminitandplan
        displayName: Terraform init and Plan
        steps:        
        - task: TerraformTask@5
          displayName: Terraform Init
          inputs:
            provider: 'azurerm'
            command: 'init'
            workingDirectory: '$(Work_dir)'
            backendServiceArm: 'testingpool'
            backendAzureRmResourceGroupName: 'rg-001'
            backendAzureRmStorageAccountName: 'machinecode'
            backendAzureRmContainerName: 'developement'
            backendAzureRmKey: 'main.terraform.tfstate'

        - task: TerraformTask@5
          displayName: Terraform Plan
          inputs:
            provider: 'azurerm'
            command: 'plan'
            workingDirectory: '$(Work_dir)'
            environmentServiceNameAzureRM: 'testingpool'

  - stage: manualvalidationandterraformapply
    displayName: Manual Validation And Terraform Apply
    jobs:
      - job: manualvalidation
        pool: server
        displayName: Manual Validation
        steps: 
        - task: ManualValidation@1
          displayName: Manual Validation
          inputs:
            notifyUsers: 'arpit39115@gmail.com'
            instructions: 'Please Review it'

      - job: terraformapply
        displayName: Terraform Apply
        steps:
        - task: TerraformTask@5
          displayName: Terraform Init
          inputs:
            provider: 'azurerm'
            command: 'init'
            workingDirectory: '$(Work_dir)'
            backendServiceArm: 'testingpool'
            backendAzureRmResourceGroupName: 'rg-001'
            backendAzureRmStorageAccountName: 'machinecode'
            backendAzureRmContainerName: 'developement'
            backendAzureRmKey: 'main.terraform.tfstate'

        - task: TerraformTask@5
          displayName: Terraform Apply
          inputs:
            provider: 'azurerm'
            command: 'apply'
            workingDirectory: '$(Work_dir)'
            environmentServiceNameAzureRM: 'testingpool'